AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for EMR Fraud Detection Pipeline

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String

Resources:
  AlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Environment}-alerts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S
        - AttributeName: account_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: severity
          AttributeType: S
      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: account-index
          KeySchema:
            - AttributeName: account_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: severity-index
          KeySchema:
            - AttributeName: severity
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  PredictionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Environment}-predictions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: prediction_id
          AttributeType: S
        - AttributeName: transaction_id
          AttributeType: S
        - AttributeName: account_id
          AttributeType: S
        - AttributeName: processed_at
          AttributeType: S
      KeySchema:
        - AttributeName: prediction_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: transaction-index
          KeySchema:
            - AttributeName: transaction_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: account-index
          KeySchema:
            - AttributeName: account_id
              KeyType: HASH
            - AttributeName: processed_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  ExecutionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Environment}-executions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: execution_id
          AttributeType: S
        - AttributeName: pipeline_name
          AttributeType: S
        - AttributeName: started_at
          AttributeType: S
      KeySchema:
        - AttributeName: execution_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: pipeline-index
          KeySchema:
            - AttributeName: pipeline_name
              KeyType: HASH
            - AttributeName: started_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  AlertsTableName:
    Description: Alerts table name
    Value: !Ref AlertsTable

  AlertsTableArn:
    Description: Alerts table ARN
    Value: !GetAtt AlertsTable.Arn

  PredictionsTableName:
    Description: Predictions table name
    Value: !Ref PredictionsTable

  PredictionsTableArn:
    Description: Predictions table ARN
    Value: !GetAtt PredictionsTable.Arn

  ExecutionsTableName:
    Description: Executions table name
    Value: !Ref ExecutionsTable

  ExecutionsTableArn:
    Description: Executions table ARN
    Value: !GetAtt ExecutionsTable.Arn
